# Generated by Django 3.2.15 on 2024-10-13 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('name_english', models.CharField(max_length=120)),
                ('name_bangla', models.CharField(blank=True, max_length=120, null=True)),
                ('code', models.PositiveIntegerField(blank=True, primary_key=True, serialize=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thana_objects', to='address.district')),
            ],
            options={
                'ordering': ['name_english'],
            },
        ),
    ]
