# Generated by Django 3.2.15 on 2024-10-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_ms', '0002_auto_20241019_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirm', 'Confirm'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
