# Generated by Django 3.2.15 on 2024-10-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_ms', '0004_alter_doctorappointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='pending', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
