# Generated by Django 3.2.15 on 2024-11-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_ms', '0005_alter_doctorappointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
