# Generated by Django 3.2.15 on 2024-12-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_ms', '0006_auto_20241126_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
