# Generated by Django 3.2.15 on 2024-10-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='updated_At',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='updated_At',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='expertize',
            old_name='updated_At',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='updated_At',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='updated_At',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='updated_At',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='updated_At',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='updated_At',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='speciality',
            old_name='updated_At',
            new_name='updated_at',
        ),
    ]
