# Generated by Django 3.2.15 on 2024-10-20 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('hospital', '0009_auto_20241020_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='thana',
        ),
        migrations.AddField(
            model_name='doctor',
            name='upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_upazila', to='address.upazila'),
        ),
    ]
