# Generated by Django 3.2.15 on 2024-10-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_auto_20241021_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='year_of_experience',
            field=models.TextField(help_text='i.e 5', max_length=4, null=True),
        ),
    ]
