# Generated by Django 3.2.15 on 2024-10-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_alter_doctor_year_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordegree',
            name='passing_year',
            field=models.CharField(help_text='Year the degree was awarded', max_length=4, verbose_name='Year of Awarded'),
        ),
    ]
