# Generated by Django 3.2.15 on 2024-10-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_alter_doctordegree_passing_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='daily_appointment_limit',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of appointments per day'),
        ),
    ]
