# Generated by Django 3.2.15 on 2024-10-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_doctor_daily_appointment_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='senderid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
