# Generated by Django 3.2.15 on 2024-11-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_auto_20241116_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='offline_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='online_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
