# Generated by Django 3.2.15 on 2024-08-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_doctor_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
