# Generated by Django 3.2.15 on 2024-08-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_slider_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='service_page_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
